"""Add profile fields

Revision ID: 0e0d9dd24ee7
Revises: d887b0168375
Create Date: 2026-06-24 10:35:21.674292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e0d9dd24ee7'
down_revision: Union[str, None] = 'd887b0168375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('date_of_birth', sa.String(length=50), nullable=True))
    op.add_column('profiles', sa.Column('linkedin_url', sa.String(length=512), nullable=True))
    op.add_column('profiles', sa.Column('github_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'github_url')
    op.drop_column('profiles', 'linkedin_url')
    op.drop_column('profiles', 'date_of_birth')
    # ### end Alembic commands ###
