"""Add job dates and notifications

Revision ID: 1bfff320c98c
Revises: 0e0d9dd24ee7
Create Date: 2026-06-24 16:12:57.498931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bfff320c98c'
down_revision: Union[str, None] = '0e0d9dd24ee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'end_date')
    op.drop_column('jobs', 'start_date')
    # ### end Alembic commands ###
