"""Add AI scores to Application

Revision ID: 32a2ff804294
Revises: 4f1c8c8d9440
Create Date: 2026-06-21 10:57:39.812249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32a2ff804294'
down_revision: Union[str, None] = '4f1c8c8d9440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
