"""Add AI scores to Application

Revision ID: 432b7e521048
Revises: 4f1c8c8d9440
Create Date: 2026-06-21 10:56:54.289238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '432b7e521048'
down_revision: Union[str, None] = '4f1c8c8d9440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('overall_score', sa.Float(), nullable=True))
    op.add_column('applications', sa.Column('experience_score', sa.Float(), nullable=True))
    op.add_column('applications', sa.Column('skills_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'skills_score')
    op.drop_column('applications', 'experience_score')
    op.drop_column('applications', 'overall_score')
    # ### end Alembic commands ###
