"""add_file_records_and_resume_file_id

Revision ID: d8255a61cb7e
Revises: 1bfff320c98c
Create Date: 2026-06-26 14:00:35.015530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8255a61cb7e'
down_revision: Union[str, None] = '1bfff320c98c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('resumes', sa.Column('file_record_id', sa.UUID(), nullable=True))
    op.alter_column('resumes', 's3_key',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.create_foreign_key(None, 'resumes', 'file_records', ['file_record_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.alter_column('resumes', 's3_key',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.drop_column('resumes', 'file_record_id')
    op.drop_table('file_records')
    # ### end Alembic commands ###
