"""Add phone and location to profile

Revision ID: d9095f2f1260
Revises: 30a75a7312bc
Create Date: 2026-06-22 10:57:28.668528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9095f2f1260'
down_revision: Union[str, None] = '30a75a7312bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('phone_number', sa.String(length=50), nullable=True))
    op.add_column('profiles', sa.Column('location', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'location')
    op.drop_column('profiles', 'phone_number')
    # ### end Alembic commands ###
